/*
Problem Description

    LeetCode - 389. Find the Difference
    
    Q. You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    let cnt1 = 0;
    let cnt2 = 0;
    let sMap = new Map();
    let tMap = new Map();

    for (let i = 0; i < s.length; i++) {
        if (sMap.get(s[i]) !== undefined) {
            sMap.set(s[i], sMap.get(s[i]) + 1);
        }
        else {
            sMap.set(s[i], cnt1 + 1);
        }
    }

    for (let j = 0; j < t.length; j++) {
        if (tMap.get(t[j]) !== undefined) {
            tMap.set(t[j], tMap.get(t[j]) + 1);
        }
        else {
            tMap.set(t[j], cnt2 + 1);
        }
    }
    
    for (let [key, value] of tMap) {
        if (sMap.get(key) !== value || sMap.get(key) === undefined) {
            return key;
        }
    }
};